spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cooperativa
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
      dialect:
        PostgreSQLDialect: org.hibernate.dialect.PostgreSQLDialect

server:
  servlet:
    context-path: /api
